import { SQLFile, SQLAnalysis } from '@/components/MultiFileSQLInput';

export interface TranslationRule {
  pattern: RegExp;
  replacement: string | ((match: string, ...groups: string[]) => string);
  description: string;
  priority: number;
}

export interface DialectTransformationSet {
  dataTypes: TranslationRule[];
  functions: TranslationRule[];
  syntax: TranslationRule[];
  operators: TranslationRule[];
  constraints: TranslationRule[];
  identifiers: TranslationRule[];
  cleanup: TranslationRule[];
}

export interface TranslationResult {
  originalContent: string;
  translatedContent: string;
  appliedRules: Array<{
    rule: string;
    description: string;
    matches: number;
  }>;
  warnings: string[];
  errors: string[];
  unsupportedFeatures: string[];
  confidence: number;
}

export interface BatchTranslationResult {
  files: Array<{
    id: string;
    name: string;
    result: TranslationResult;
  }>;
  globalWarnings: string[];
  dependencyOrder: string[];
  estimatedExecutionTime: string;
}

// Advanced SQL Translation Engine
export class SQLTranslationEngine {
  private transformationSets: Record<string, Record<string, DialectTransformationSet>> = {};

  constructor() {
    this.initializeTransformationSets();
  }

  private initializeTransformationSets() {
    // MySQL to PostgreSQL transformations
    this.transformationSets['mysql'] = {
      postgresql: {
        dataTypes: [
          {
            pattern: /\bINT\s+AUTO_INCREMENT\b/gi,
            replacement: 'SERIAL',
            description: 'Convert MySQL AUTO_INCREMENT INT to PostgreSQL SERIAL',
            priority: 10
          },
          {
            pattern: /\bBIGINT\s+AUTO_INCREMENT\b/gi,
            replacement: 'BIGSERIAL',
            description: 'Convert MySQL AUTO_INCREMENT BIGINT to PostgreSQL BIGSERIAL',
            priority: 10
          },
          {
            pattern: /\bAUTO_INCREMENT\b/gi,
            replacement: 'GENERATED BY DEFAULT AS IDENTITY',
            description: 'Convert MySQL AUTO_INCREMENT to PostgreSQL IDENTITY',
            priority: 9
          },
          {
            pattern: /\bTINYINT\(1\)\b/gi,
            replacement: 'BOOLEAN',
            description: 'Convert MySQL TINYINT(1) to PostgreSQL BOOLEAN',
            priority: 8
          },
          {
            pattern: /\bTINYINT(?:\(\d+\))?\b/gi,
            replacement: 'SMALLINT',
            description: 'Convert MySQL TINYINT to PostgreSQL SMALLINT',
            priority: 7
          },
          {
            pattern: /\bMEDIUMINT(?:\(\d+\))?\b/gi,
            replacement: 'INTEGER',
            description: 'Convert MySQL MEDIUMINT to PostgreSQL INTEGER',
            priority: 7
          },
          {
            pattern: /\bDATETIME\b/gi,
            replacement: 'TIMESTAMP',
            description: 'Convert MySQL DATETIME to PostgreSQL TIMESTAMP',
            priority: 6
          },
          {
            pattern: /\bLONGTEXT\b/gi,
            replacement: 'TEXT',
            description: 'Convert MySQL LONGTEXT to PostgreSQL TEXT',
            priority: 6
          },
          {
            pattern: /\bMEDIUMTEXT\b/gi,
            replacement: 'TEXT',
            description: 'Convert MySQL MEDIUMTEXT to PostgreSQL TEXT',
            priority: 6
          },
          {
            pattern: /\bTINYTEXT\b/gi,
            replacement: 'VARCHAR(255)',
            description: 'Convert MySQL TINYTEXT to PostgreSQL VARCHAR(255)',
            priority: 6
          },
          {
            pattern: /\bDOUBLE\b/gi,
            replacement: 'DOUBLE PRECISION',
            description: 'Convert MySQL DOUBLE to PostgreSQL DOUBLE PRECISION',
            priority: 5
          },
          {
            pattern: /\bFLOAT\b/gi,
            replacement: 'REAL',
            description: 'Convert MySQL FLOAT to PostgreSQL REAL',
            priority: 5
          },
          {
            pattern: /\bJSON\b/gi,
            replacement: 'JSONB',
            description: 'Convert MySQL JSON to PostgreSQL JSONB for better performance',
            priority: 5
          }
        ],
        functions: [
          {
            pattern: /\bNOW\s*\(\s*\)/gi,
            replacement: 'CURRENT_TIMESTAMP',
            description: 'Convert MySQL NOW() to PostgreSQL CURRENT_TIMESTAMP',
            priority: 8
          },
          {
            pattern: /\bIFNULL\s*\(/gi,
            replacement: 'COALESCE(',
            description: 'Convert MySQL IFNULL to PostgreSQL COALESCE',
            priority: 8
          },
          {
            pattern: /\bDATE_FORMAT\s*\(\s*([^,]+),\s*'%Y-%m'\s*\)/gi,
            replacement: "TO_CHAR($1, 'YYYY-MM')",
            description: 'Convert MySQL DATE_FORMAT to PostgreSQL TO_CHAR',
            priority: 9
          },
          {
            pattern: /\bDATE_SUB\s*\(\s*([^,]+),\s*INTERVAL\s+(\d+)\s+(\w+)\s*\)/gi,
            replacement: (match, date, amount, unit) => {
              const unitMap: Record<string, string> = {
                'DAY': 'days',
                'MONTH': 'months',
                'YEAR': 'years',
                'HOUR': 'hours',
                'MINUTE': 'minutes',
                'SECOND': 'seconds'
              };
              const pgUnit = unitMap[unit.toUpperCase()] || unit.toLowerCase();
              return `${date} - INTERVAL '${amount} ${pgUnit}'`;
            },
            description: 'Convert MySQL DATE_SUB to PostgreSQL interval subtraction',
            priority: 9
          },
          {
            pattern: /\bDATE_ADD\s*\(\s*([^,]+),\s*INTERVAL\s+(\d+)\s+(\w+)\s*\)/gi,
            replacement: (match, date, amount, unit) => {
              const unitMap: Record<string, string> = {
                'DAY': 'days',
                'MONTH': 'months',
                'YEAR': 'years',
                'HOUR': 'hours',
                'MINUTE': 'minutes',
                'SECOND': 'seconds'
              };
              const pgUnit = unitMap[unit.toUpperCase()] || unit.toLowerCase();
              return `${date} + INTERVAL '${amount} ${pgUnit}'`;
            },
            description: 'Convert MySQL DATE_ADD to PostgreSQL interval addition',
            priority: 9
          },
          {
            pattern: /\bCURDATE\s*\(\s*\)/gi,
            replacement: 'CURRENT_DATE',
            description: 'Convert MySQL CURDATE() to PostgreSQL CURRENT_DATE',
            priority: 7
          },
          {
            pattern: /\bCURTIME\s*\(\s*\)/gi,
            replacement: 'CURRENT_TIME',
            description: 'Convert MySQL CURTIME() to PostgreSQL CURRENT_TIME',
            priority: 7
          }
        ],
        syntax: [
          {
            pattern: /\bLIMIT\s+(\d+)\s*,\s*(\d+)\b/gi,
            replacement: 'LIMIT $2 OFFSET $1',
            description: 'Convert MySQL LIMIT offset,count to PostgreSQL LIMIT count OFFSET offset',
            priority: 10
          },
          {
            pattern: /\bUNSIGNED\b/gi,
            replacement: '',
            description: 'Remove MySQL UNSIGNED keyword (not supported in PostgreSQL)',
            priority: 6
          },
          {
            pattern: /\bENGINE\s*=\s*\w+/gi,
            replacement: '',
            description: 'Remove MySQL ENGINE specification',
            priority: 5
          },
          {
            pattern: /\bDEFAULT\s+CHARSET\s*=\s*[\w\d_]+/gi,
            replacement: '',
            description: 'Remove MySQL DEFAULT CHARSET specification',
            priority: 5
          },
          {
            pattern: /\bCOLLATE\s*=\s*[\w\d_]+/gi,
            replacement: '',
            description: 'Remove MySQL COLLATE specification',
            priority: 5
          },
          {
            pattern: /\bCOMMENT\s*=\s*'([^']*)'/gi,
            replacement: '',
            description: 'Remove MySQL table/column comments (convert to PostgreSQL format later)',
            priority: 4
          }
        ],
        operators: [
          {
            pattern: /`([^`]+)`/g,
            replacement: '"$1"',
            description: 'Convert MySQL backticks to PostgreSQL double quotes',
            priority: 8
          }
        ],
        constraints: [
          {
            pattern: /\bENUM\s*\(\s*([^)]+)\s*\)/gi,
            replacement: (match, values) => {
              return `VARCHAR(50) CHECK (VALUE IN (${values}))`;
            },
            description: 'Convert MySQL ENUM to PostgreSQL CHECK constraint',
            priority: 9
          }
        ],
        identifiers: [
          {
            pattern: /\b([a-zA-Z_][a-zA-Z0-9_]*)\s*\.\s*([a-zA-Z_][a-zA-Z0-9_]*)/g,
            replacement: '"$1"."$2"',
            description: 'Quote schema.table identifiers for PostgreSQL',
            priority: 3
          }
        ],
        cleanup: [
          {
            pattern: /,\s*,/g,
            replacement: ',',
            description: 'Remove double commas from cleanup operations',
            priority: 1
          },
          {
            pattern: /\s+/g,
            replacement: ' ',
            description: 'Normalize whitespace',
            priority: 1
          },
          {
            pattern: /;\s*;/g,
            replacement: ';',
            description: 'Remove double semicolons',
            priority: 1
          }
        ]
      },
      snowflake: {
        dataTypes: [
          {
            pattern: /\bAUTO_INCREMENT\b/gi,
            replacement: 'AUTOINCREMENT',
            description: 'Convert MySQL AUTO_INCREMENT to Snowflake AUTOINCREMENT',
            priority: 10
          },
          {
            pattern: /\bTINYINT(?:\(\d+\))?\b/gi,
            replacement: 'SMALLINT',
            description: 'Convert MySQL TINYINT to Snowflake SMALLINT',
            priority: 8
          },
          {
            pattern: /\bMEDIUMINT(?:\(\d+\))?\b/gi,
            replacement: 'INT',
            description: 'Convert MySQL MEDIUMINT to Snowflake INT',
            priority: 8
          },
          {
            pattern: /\bLONGTEXT\b/gi,
            replacement: 'TEXT',
            description: 'Convert MySQL LONGTEXT to Snowflake TEXT',
            priority: 7
          },
          {
            pattern: /\bDATETIME\b/gi,
            replacement: 'TIMESTAMP',
            description: 'Convert MySQL DATETIME to Snowflake TIMESTAMP',
            priority: 7
          },
          {
            pattern: /\bJSON\b/gi,
            replacement: 'VARIANT',
            description: 'Convert MySQL JSON to Snowflake VARIANT',
            priority: 7
          }
        ],
        functions: [
          {
            pattern: /\bNOW\s*\(\s*\)/gi,
            replacement: 'CURRENT_TIMESTAMP()',
            description: 'Convert MySQL NOW() to Snowflake CURRENT_TIMESTAMP()',
            priority: 8
          },
          {
            pattern: /\bDATE_FORMAT\s*\(\s*([^,]+),\s*'%Y-%m'\s*\)/gi,
            replacement: "TO_CHAR($1, 'YYYY-MM')",
            description: 'Convert MySQL DATE_FORMAT to Snowflake TO_CHAR',
            priority: 9
          },
          {
            pattern: /\bDATE_SUB\s*\(\s*([^,]+),\s*INTERVAL\s+(\d+)\s+(\w+)\s*\)/gi,
            replacement: (match, date, amount, unit) => {
              const unitMap: Record<string, string> = {
                'DAY': 'DAY',
                'MONTH': 'MONTH',
                'YEAR': 'YEAR',
                'HOUR': 'HOUR',
                'MINUTE': 'MINUTE',
                'SECOND': 'SECOND'
              };
              const sfUnit = unitMap[unit.toUpperCase()] || unit.toUpperCase();
              return `DATEADD(${sfUnit}, -${amount}, ${date})`;
            },
            description: 'Convert MySQL DATE_SUB to Snowflake DATEADD',
            priority: 9
          }
        ],
        syntax: [
          {
            pattern: /\bENGINE\s*=\s*\w+/gi,
            replacement: '',
            description: 'Remove MySQL ENGINE specification',
            priority: 5
          },
          {
            pattern: /\bDEFAULT\s+CHARSET\s*=\s*[\w\d_]+/gi,
            replacement: '',
            description: 'Remove MySQL DEFAULT CHARSET specification',
            priority: 5
          }
        ],
        operators: [
          {
            pattern: /`([^`]+)`/g,
            replacement: '"$1"',
            description: 'Convert MySQL backticks to Snowflake double quotes',
            priority: 8
          }
        ],
        constraints: [],
        identifiers: [],
        cleanup: [
          {
            pattern: /,\s*,/g,
            replacement: ',',
            description: 'Remove double commas from cleanup operations',
            priority: 1
          }
        ]
      }
    };

    // PostgreSQL to MySQL transformations
    this.transformationSets['postgresql'] = {
      mysql: {
        dataTypes: [
          {
            pattern: /\bSERIAL\b/gi,
            replacement: 'INT AUTO_INCREMENT',
            description: 'Convert PostgreSQL SERIAL to MySQL INT AUTO_INCREMENT',
            priority: 10
          },
          {
            pattern: /\bBIGSERIAL\b/gi,
            replacement: 'BIGINT AUTO_INCREMENT',
            description: 'Convert PostgreSQL BIGSERIAL to MySQL BIGINT AUTO_INCREMENT',
            priority: 10
          },
          {
            pattern: /\bBOOLEAN\b/gi,
            replacement: 'TINYINT(1)',
            description: 'Convert PostgreSQL BOOLEAN to MySQL TINYINT(1)',
            priority: 8
          },
          {
            pattern: /\bTIMESTAMP\b/gi,
            replacement: 'DATETIME',
            description: 'Convert PostgreSQL TIMESTAMP to MySQL DATETIME',
            priority: 7
          },
          {
            pattern: /\bDOUBLE\s+PRECISION\b/gi,
            replacement: 'DOUBLE',
            description: 'Convert PostgreSQL DOUBLE PRECISION to MySQL DOUBLE',
            priority: 7
          },
          {
            pattern: /\bREAL\b/gi,
            replacement: 'FLOAT',
            description: 'Convert PostgreSQL REAL to MySQL FLOAT',
            priority: 7
          },
          {
            pattern: /\bJSONB\b/gi,
            replacement: 'JSON',
            description: 'Convert PostgreSQL JSONB to MySQL JSON',
            priority: 7
          }
        ],
        functions: [
          {
            pattern: /\bCURRENT_TIMESTAMP\b/gi,
            replacement: 'NOW()',
            description: 'Convert PostgreSQL CURRENT_TIMESTAMP to MySQL NOW()',
            priority: 8
          },
          {
            pattern: /\bCOALESCE\s*\(/gi,
            replacement: 'IFNULL(',
            description: 'Convert PostgreSQL COALESCE to MySQL IFNULL',
            priority: 8
          }
        ],
        syntax: [
          {
            pattern: /\bLIMIT\s+(\d+)\s+OFFSET\s+(\d+)\b/gi,
            replacement: 'LIMIT $2, $1',
            description: 'Convert PostgreSQL LIMIT/OFFSET to MySQL LIMIT offset,count',
            priority: 10
          }
        ],
        operators: [
          {
            pattern: /"([^"]+)"/g,
            replacement: '`$1`',
            description: 'Convert PostgreSQL double quotes to MySQL backticks',
            priority: 8
          }
        ],
        constraints: [],
        identifiers: [],
        cleanup: []
      }
    };

    // Add more transformation sets for other dialects...
    this.addSQLServerTransformations();
    this.addOracleTransformations();
    this.addSnowflakeTransformations();
  }

  private addSQLServerTransformations() {
    // MySQL to SQL Server
    this.transformationSets['mysql']['mssql'] = {
      dataTypes: [
        {
          pattern: /\bAUTO_INCREMENT\b/gi,
          replacement: 'IDENTITY(1,1)',
          description: 'Convert MySQL AUTO_INCREMENT to SQL Server IDENTITY',
          priority: 10
        },
        {
          pattern: /\bBOOLEAN\b/gi,
          replacement: 'BIT',
          description: 'Convert to SQL Server BIT',
          priority: 8
        },
        {
          pattern: /\bTEXT\b/gi,
          replacement: 'NVARCHAR(MAX)',
          description: 'Convert TEXT to SQL Server NVARCHAR(MAX)',
          priority: 7
        }
      ],
      functions: [
        {
          pattern: /\bNOW\s*\(\s*\)/gi,
          replacement: 'GETDATE()',
          description: 'Convert MySQL NOW() to SQL Server GETDATE()',
          priority: 8
        }
      ],
      syntax: [
        {
          pattern: /\bLIMIT\s+(\d+)\b/gi,
          replacement: 'TOP $1',
          description: 'Convert MySQL LIMIT to SQL Server TOP',
          priority: 10
        }
      ],
      operators: [
        {
          pattern: /`([^`]+)`/g,
          replacement: '[$1]',
          description: 'Convert MySQL backticks to SQL Server square brackets',
          priority: 8
        }
      ],
      constraints: [],
      identifiers: [],
      cleanup: []
    };
  }

  private addOracleTransformations() {
    // MySQL to Oracle
    this.transformationSets['mysql']['oracle'] = {
      dataTypes: [
        {
          pattern: /\bAUTO_INCREMENT\b/gi,
          replacement: 'GENERATED BY DEFAULT AS IDENTITY',
          description: 'Convert MySQL AUTO_INCREMENT to Oracle IDENTITY',
          priority: 10
        },
        {
          pattern: /\bBOOLEAN\b/gi,
          replacement: 'NUMBER(1)',
          description: 'Convert to Oracle NUMBER(1)',
          priority: 8
        },
        {
          pattern: /\bTEXT\b/gi,
          replacement: 'CLOB',
          description: 'Convert TEXT to Oracle CLOB',
          priority: 7
        },
        {
          pattern: /\bVARCHAR\((\d+)\)/gi,
          replacement: 'VARCHAR2($1)',
          description: 'Convert VARCHAR to Oracle VARCHAR2',
          priority: 7
        }
      ],
      functions: [
        {
          pattern: /\bNOW\s*\(\s*\)/gi,
          replacement: 'SYSDATE',
          description: 'Convert MySQL NOW() to Oracle SYSDATE',
          priority: 8
        }
      ],
      syntax: [
        {
          pattern: /\bLIMIT\s+(\d+)\b/gi,
          replacement: 'AND ROWNUM <= $1',
          description: 'Convert MySQL LIMIT to Oracle ROWNUM',
          priority: 10
        }
      ],
      operators: [
        {
          pattern: /`([^`]+)`/g,
          replacement: '"$1"',
          description: 'Convert MySQL backticks to Oracle double quotes',
          priority: 8
        }
      ],
      constraints: [],
      identifiers: [],
      cleanup: []
    };
  }

  private addSnowflakeTransformations() {
    // PostgreSQL to Snowflake
    this.transformationSets['postgresql']['snowflake'] = {
      dataTypes: [
        {
          pattern: /\bSERIAL\b/gi,
          replacement: 'AUTOINCREMENT',
          description: 'Convert PostgreSQL SERIAL to Snowflake AUTOINCREMENT',
          priority: 10
        },
        {
          pattern: /\bBIGSERIAL\b/gi,
          replacement: 'AUTOINCREMENT',
          description: 'Convert PostgreSQL BIGSERIAL to Snowflake AUTOINCREMENT',
          priority: 10
        },
        {
          pattern: /\bTIMESTAMP\s+WITH\s+TIME\s+ZONE\b/gi,
          replacement: 'TIMESTAMP_TZ',
          description: 'Convert PostgreSQL TIMESTAMP WITH TIME ZONE to Snowflake TIMESTAMP_TZ',
          priority: 8
        }
      ],
      functions: [
        {
          pattern: /\bCURRENT_TIMESTAMP\b/gi,
          replacement: 'CURRENT_TIMESTAMP()',
          description: 'Convert PostgreSQL CURRENT_TIMESTAMP to Snowflake CURRENT_TIMESTAMP()',
          priority: 8
        }
      ],
      syntax: [],
      operators: [],
      constraints: [],
      identifiers: [],
      cleanup: []
    };
  }

  // Main translation method
  public translateSQL(
    content: string, 
    sourceDialect: string, 
    targetDialect: string
  ): TranslationResult {
    const appliedRules: Array<{ rule: string; description: string; matches: number }> = [];
    const warnings: string[] = [];
    const errors: string[] = [];
    const unsupportedFeatures: string[] = [];
    
    let translatedContent = content;
    
    // Get transformation set
    const transformationSet = this.transformationSets[sourceDialect]?.[targetDialect];
    
    if (!transformationSet) {
      errors.push(`No transformation rules available for ${sourceDialect} to ${targetDialect}`);
      return {
        originalContent: content,
        translatedContent: content,
        appliedRules: [],
        warnings,
        errors,
        unsupportedFeatures,
        confidence: 0
      };
    }

    // Add translation header
    const timestamp = new Date().toISOString();
    const header = `-- Translated from ${sourceDialect.toUpperCase()} to ${targetDialect.toUpperCase()}\n-- Generated: ${timestamp}\n-- Translation Engine v2.0\n\n`;
    
    // Apply transformations in order of priority
    const allRules = [
      ...transformationSet.dataTypes,
      ...transformationSet.functions,
      ...transformationSet.syntax,
      ...transformationSet.operators,
      ...transformationSet.constraints,
      ...transformationSet.identifiers,
      ...transformationSet.cleanup
    ].sort((a, b) => b.priority - a.priority);

    allRules.forEach(rule => {
      const beforeLength = translatedContent.length;
      const matches = (translatedContent.match(rule.pattern) || []).length;
      
      if (matches > 0) {
        if (typeof rule.replacement === 'function') {
          translatedContent = translatedContent.replace(rule.pattern, rule.replacement);
        } else {
          translatedContent = translatedContent.replace(rule.pattern, rule.replacement);
        }
        
        appliedRules.push({
          rule: rule.pattern.toString(),
          description: rule.description,
          matches
        });
      }
    });

    // Post-processing cleanup
    translatedContent = this.postProcessCleanup(translatedContent);
    
    // Calculate confidence based on successful transformations
    const confidence = Math.min(95, Math.max(10, (appliedRules.length / allRules.length) * 100));
    
    // Add warnings for potential issues
    this.addTranslationWarnings(content, sourceDialect, targetDialect, warnings, unsupportedFeatures);
    
    return {
      originalContent: content,
      translatedContent: header + translatedContent,
      appliedRules,
      warnings,
      errors,
      unsupportedFeatures,
      confidence: Math.round(confidence)
    };
  }

  // Batch translation for multiple files
  public translateBatch(
    files: SQLFile[],
    targetDialect: string,
    onProgress?: (progress: number, currentFile: string) => void
  ): Promise<BatchTranslationResult> {
    return new Promise((resolve) => {
      const results: BatchTranslationResult = {
        files: [],
        globalWarnings: [],
        dependencyOrder: [],
        estimatedExecutionTime: '5-15 minutes'
      };

      // Analyze dependencies and create execution order
      const dependencyOrder = this.resolveDependencies(files);
      results.dependencyOrder = dependencyOrder;

      // Translate files in dependency order
      let completed = 0;
      const total = files.length;

      files.forEach((file, index) => {
        setTimeout(() => {
          onProgress?.(Math.round((completed / total) * 100), file.name);
          
          const translationResult = this.translateSQL(
            file.content,
            file.detectedDialect,
            targetDialect
          );

          results.files.push({
            id: file.id,
            name: file.name,
            result: translationResult
          });

          completed++;
          
          if (completed === total) {
            // Add global warnings
            this.addGlobalWarnings(files, results);
            resolve(results);
          }
        }, index * 100); // Stagger processing
      });
    });
  }

  private postProcessCleanup(content: string): string {
    return content
      // Normalize line endings
      .replace(/\r\n/g, '\n')
      .replace(/\r/g, '\n')
      
      // Clean up extra whitespace
      .replace(/\s+/g, ' ')
      .replace(/\s*;\s*/g, ';\n')
      
      // Format SQL keywords
      .replace(/\b(SELECT|FROM|WHERE|JOIN|LEFT JOIN|RIGHT JOIN|INNER JOIN|ORDER BY|GROUP BY|HAVING)\b/gi, 
        match => match.toUpperCase())
      
      // Clean up commas and parentheses
      .replace(/,\s*,/g, ',')
      .replace(/\(\s+/g, '(')
      .replace(/\s+\)/g, ')')
      
      // Remove empty lines
      .replace(/\n\s*\n/g, '\n')
      .trim();
  }

  private addTranslationWarnings(
    content: string, 
    sourceDialect: string, 
    targetDialect: string, 
    warnings: string[], 
    unsupportedFeatures: string[]
  ) {
    const upperContent = content.toUpperCase();

    // Check for potentially problematic patterns
    if (sourceDialect === 'mysql' && targetDialect === 'postgresql') {
      if (upperContent.includes('ENUM(')) {
        warnings.push('ENUM types converted to CHECK constraints - verify constraint logic');
      }
      if (upperContent.includes('FULLTEXT')) {
        unsupportedFeatures.push('FULLTEXT indexes - consider using PostgreSQL full-text search');
      }
      if (upperContent.includes('SPATIAL')) {
        unsupportedFeatures.push('SPATIAL indexes - consider using PostGIS extension');
      }
    }

    if (sourceDialect === 'mysql' && targetDialect === 'snowflake') {
      if (upperContent.includes('TRIGGER')) {
        unsupportedFeatures.push('Triggers - Snowflake uses tasks and streams instead');
      }
      if (upperContent.includes('PROCEDURE')) {
        warnings.push('Stored procedures - verify Snowflake JavaScript/SQL procedure syntax');
      }
    }

    // General warnings
    if (upperContent.includes('SELECT *')) {
      warnings.push('SELECT * statements found - specify columns for better performance');
    }
    
    if (content.match(/WHERE.*=.*NULL/i)) {
      warnings.push('Potential NULL comparison issue - use IS NULL instead of = NULL');
    }
  }

  private resolveDependencies(files: SQLFile[]): string[] {
    // Simple dependency resolution based on CREATE/DROP order
    const createFiles = files.filter(f => f.content.toUpperCase().includes('CREATE'));
    const otherFiles = files.filter(f => !f.content.toUpperCase().includes('CREATE'));
    
    // Tables first, then views, then procedures/functions
    const tables = createFiles.filter(f => f.content.toUpperCase().includes('CREATE TABLE'));
    const views = createFiles.filter(f => f.content.toUpperCase().includes('CREATE VIEW'));
    const procedures = createFiles.filter(f => 
      f.content.toUpperCase().includes('CREATE PROCEDURE') || 
      f.content.toUpperCase().includes('CREATE FUNCTION')
    );
    
    return [
      ...tables.map(f => f.name),
      ...views.map(f => f.name),
      ...procedures.map(f => f.name),
      ...otherFiles.map(f => f.name)
    ];
  }

  private addGlobalWarnings(files: SQLFile[], results: BatchTranslationResult) {
    const totalErrors = results.files.reduce((sum, f) => sum + f.result.errors.length, 0);
    const totalWarnings = results.files.reduce((sum, f) => sum + f.result.warnings.length, 0);
    
    if (totalErrors > 0) {
      results.globalWarnings.push(`${totalErrors} translation errors found across all files`);
    }
    
    if (totalWarnings > 5) {
      results.globalWarnings.push(`${totalWarnings} warnings generated - review before production use`);
    }
    
    // Check for cross-file dependencies
    const tableNames = new Set<string>();
    files.forEach(file => {
      if (file.analysis) {
        file.analysis.tables.forEach(table => tableNames.add(table.toLowerCase()));
      }
    });
    
    if (tableNames.size > 20) {
      results.globalWarnings.push('Large number of tables detected - consider breaking into smaller migration batches');
    }
  }
}

// Export singleton instance
export const sqlTranslationEngine = new SQLTranslationEngine();