"""Add firebase_uid to users table

Revision ID: d4b68fd64aa1
Revises: 142cac453367
Create Date: 2025-09-17 17:24:05.753181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4b68fd64aa1'
down_revision: Union[str, Sequence[str], None] = '142cac453367'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firebase_uid', sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint('uq_users_firebase_uid', ['firebase_uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('uq_users_firebase_uid', type_='unique')
        batch_op.drop_column('firebase_uid')
    # ### end Alembic commands ###
