"""Remove hashed_password column from users table

Revision ID: e7f9a8b3c4d2
Revises: d4b68fd64aa1
Create Date: 2025-10-28 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7f9a8b3c4d2'
down_revision: Union[str, Sequence[str], None] = 'd4b68fd64aa1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema - Remove hashed_password column as we now use Firebase authentication."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema - Add back hashed_password column."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hashed_password', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###
